# Generated by Django 5.1.6 on 2025-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sUsername', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('achievement', 'achievement'), ('placement', 'placement'), ('certificate', 'certificate')], max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=4)),
                ('year', models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2, null=True)),
                ('files', models.JSONField(default=list)),
            ],
        ),
    ]
