# Generated by Django 5.1.6 on 2025-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('achv', 'achievements'), ('plcm', 'placements'), ('crtf', 'certificates')], max_length=5)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
