# Generated by Django 5.1.6 on 2025-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(default='EXTC', max_length=4),
        ),
    ]
