# Generated by Django 5.1.6 on 2025-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='doe',
            field=models.DateField(null=True),
        ),
    ]
