# Generated by Django 5.1.6 on 2025-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_doe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('mark', models.CharField(default='P', max_length=1)),
                ('roll_image', models.URLField()),
                ('roll_date', models.DateField()),
            ],
        ),
    ]
