# Generated by Django 5.1.6 on 2025-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(max_length=4),
        ),
    ]
