# Generated by Django 5.1.6 on 2025-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2, null=True),
        ),
    ]
