# Generated by Django 5.1.6 on 2025-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
