# Generated by Django 5.1.6 on 2025-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='s_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
