# Generated by Django 5.1.6 on 2025-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='mark',
        ),
        migrations.AddField(
            model_name='attend',
            name='at',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='cn',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='coa',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='math',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='os',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='python',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
