# Generated by Django 5.1.6 on 2025-03-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_s_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='s_username',
            new_name='sUsername',
        ),
    ]
