# Generated by Django 5.1.6 on 2025-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_attend_at_alter_attend_cn_alter_attend_coa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='at',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='attend',
            name='cn',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='attend',
            name='coa',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='attend',
            name='math',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='attend',
            name='os',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='attend',
            name='python',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
