# Generated by Django 5.1.6 on 2025-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_item_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
