# Generated by Django 5.1.6 on 2025-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('EXTC', 'EXTC'), ('IT', 'IT'), ('CSE', 'CSE'), ('CS', 'CS')], default='EXTC', max_length=10),
        ),
    ]
