# Generated by Django 5.1.6 on 2025-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_member_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='roll_no',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
