# Generated by Django 5.1.6 on 2025-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_email_remove_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
